name: Release Automation

on:
  push:
    tags:
      - 'v*'  # Запускаем при пуше тега, начинающегося на 'v'

permissions:
  contents: write

jobs:
  create_and_upload:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: "Release ${{ github.ref }}"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset(s)
        uses: sekwah41/upload-release-assets@v1.1.0
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './system.json'
          asset_name: 'system.json'
          asset_content_type: 'application/json'
          token: ${{ secrets.GITHUB_TOKEN }}
