name: Release System File

on:
  push:
    tags:
      - 'v*'  # Срабатываем, когда пушите тег, начинающийся на "v"

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Создадим релиз (если он еще не создан). 
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: "Release ${{ github.ref }}"
          draft: false
          prerelease: false
          body: "Автоматический релиз для version ${{ github.ref }}"

      # Загрузим нужный файл (например, system.json) как ассет релиза.
      - name: Upload System.json
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './system.json'
          asset_name: 'system.json'
          asset_content_type: 'application/json'
