name: Release Automation

on:
  push:
    branches: [ main ]  # Можно указать конкретную ветку или убрать, чтобы реагировать на пуш в любую ветку

permissions:
  contents: write

jobs:
  create_and_upload:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Создаём тег на основе хэша коммита
      - name: Define Tag
      - run: echo "TAG=build-${{ github.sha }}" >> $GITHUB_ENV
      - run:  zip ${{ env.ZIP_NAME }} -r lang module packs styles templates system.json


      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "auto-${{ github.run_id }}"
          name: "Release for run ${{ github.run_id }}"
          draft: false
          prerelease: false

      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          omitDraftDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './system.json, ./${{ env.ZIP_NAME }}'
          tag: Release for run ${{ github.run_id }}
          body: |
            ${{ steps.release.outputs.body }}
