name: Release Automation

on:
  push:
    branches: [ main ]  # Можно указать конкретную ветку или убрать, чтобы реагировать на пуш в любую ветку

permissions:
  contents: write

jobs:
  create_and_upload:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Создаём тег на основе хэша коммита
      - name: Define Tag
        run: echo "TAG=build-${{ github.sha }}" >> $GITHUB_ENV
      - run: zip ${{ env.ZIP_NAME }} -r lang module packs styles templates system.json


      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "auto-${{ github.run_id }}"
          name: "Release for run ${{ github.run_id }}"
          draft: false
          prerelease: false

      # Загружаем ZIP-файл в релиз
      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './${{ env.ZIP_NAME }}'
          asset_name: './${{ env.ZIP_NAME }}'
          asset_content_type: 'application/zip'

      # Загружаем system.json в релиз
      - name: Upload system.json to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './system.json'
          asset_name: 'system.json'
          asset_content_type: 'application/json'
