name: Release Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release directory
        run: mkdir -p release

      - name: Copy system file
        run: cp ./system.json ./release/system.json

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset(s)
        uses: sekwah41/upload-release-assets@v1.1.0
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/system.json
          asset_name: system.json
          asset_content_type: application/json
