name: Release Automation

on:
  push:
    branches: [ main ]  # Можно указать конкретную ветку или убрать, чтобы реагировать на пуш в любую ветку

permissions:
  contents: write

jobs:
  create_and_upload:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Создаём тег на основе хэша коммита
      - name: Define Tag
        run: echo "TAG=build-${{ github.sha }}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG }}
          release_name: "Release for commit ${{ github.sha }}"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset(s)
        uses: sekwah41/upload-release-assets@v1.1.0
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './system.json'
          asset_name: 'system.json'
          asset_content_type: 'application/json'
          token: ${{ secrets.GITHUB_TOKEN }}
