name: Release Automation

on:
  push:
    branches: [ main ]  # Можно указать конкретную ветку или убрать, чтобы реагировать на пуш в любую ветку

permissions:
  contents: write

jobs:
  create_and_upload:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Создаём тег на основе хэша коммита
      - name: Define Tag
        run: echo "TAG=build-${{ github.sha }}" >> $GITHUB_ENV
      - run: zip ${{ env.ZIP_NAME }} -r lang module packs styles templates system.json


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.TAG }}
          release_name: "Release for commit ${{ github.sha }}"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

   - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # Set this to false if you want to prevent updating existing releases
        name: ${{ env.TAG_NAME }}
        draft: false
        prerelease: true
        omitDraftDuringUpdate: true
        omitPrereleaseDuringUpdate: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './system.json, ./${{ env.ZIP_NAME }}'
        tag: ${{ env.TAG_NAME }}
        body: |
          ${{ steps.release.outputs.body }}
