            - name: Upload Release Asset(s)
  # You may pin to the exact commit or the version.
  # uses: sekwah41/upload-release-assets@c567fc0fd9cbda3da23f1b498ee7f0446b649aed
  uses: sekwah41/upload-release-assets@v1.1.0
  with:
    # The URL for uploading assets to the release.
    upload_url: 
    # The path to the asset you want to upload
    asset_path: 
    # The name of the asset you want to upload
    asset_name: system.json
          
